spring.application.name=catalog-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/sweet_treats
spring.datasource.username=root
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true